name: debug-tools

executables:
  debug-args:
    main: debug-args.hs
    dependencies:
      - base
  debug-signals:
    main: debug-signals.hs
    dependencies:
      - base
      - containers
      - unix
